# Generated by Django 3.2.21 on 2023-10-01 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='school_images/')),
            ],
            options={
                'ordering': ['school_name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('requested_date', models.DateField()),
                ('requested_time', models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:10', '15:10'), ('16:00', '16:00'), ('16:30', '16:30')], default='12:00', max_length=25)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('status', models.CharField(choices=[('Lesson Time Confirmed', 'Lesson Time Confirmed'), ('Lesson Time Rejected', 'Lesson Time Rejected'), ('Lesson Time Expired', 'Lesson Time Expired')], default='Lesson Confirmed', max_length=25)),
                ('surfer_count', models.IntegerField(choices=[(1, '1 surfer'), (2, '2 surfers'), (3, '3 surfers'), (4, '4 surfers')], default=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surf_school_name', to='bookings.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_time'],
                'unique_together': {('requested_date', 'requested_time', 'school')},
            },
        ),
    ]
