# Generated by Django 3.2.21 on 2023-10-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
