# Generated by Django 3.2.21 on 2023-10-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_school_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booking Confirmed', 'Booking Confirmed'), ('Booking Rejected', 'Booking Rejected'), ('Awaiting Confirmation', 'Awaiting Confirmation')], default='Booking Confirmed', max_length=25),
        ),
    ]
